# Generated by Django 5.0 on 2024-04-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
