# Generated by Django 5.0 on 2024-01-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(default=1, max_length=100, verbose_name='transaction_code'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='basket',
            field=models.ManyToManyField(related_name='BasketItem', to='order.basket'),
        ),
    ]
