# Generated by Django 5.0 on 2024-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ManyToManyField(related_name='CartItem', to='order.cart'),
        ),
    ]
