# Generated by Django 5.0 on 2024-03-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_cart_product_cart_quantity_delete_cartitem'),
        ('products', '0024_rename_kod_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.product'),
        ),
    ]
