# Generated by Django 5.0 on 2024-04-01 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_shippingadress_adress_shippingadress_address'),
        ('order', '0009_alter_cart_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=100, verbose_name='transaction_code')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='accounts.shippingadress')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='order.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Check_out',
        ),
    ]
