# Generated by Django 5.0 on 2023-12-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='firstName')),
                ('lastName', models.CharField(blank=True, max_length=100, null=True, verbose_name='lastName')),
                ('fullName', models.CharField(blank=True, max_length=200, null=True, verbose_name='fullName')),
                ('number', models.CharField(max_length=30, verbose_name='number')),
                ('email', models.EmailField(max_length=40, verbose_name='email')),
                ('message', models.TextField(max_length=255, verbose_name='message')),
            ],
        ),
    ]
