# Generated by Django 5.0 on 2024-02-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogreview',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fullName',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogReview',
        ),
    ]
