# Generated by Django 5.0 on 2024-01-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_size_remove_product_price_productversion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizerelation',
            name='product_version',
        ),
        migrations.RemoveField(
            model_name='productsizerelation',
            name='size',
        ),
        migrations.AddField(
            model_name='productversion',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductVersion', to='products.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productversion',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductVersion', to='products.size'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductColorRelation',
        ),
        migrations.DeleteModel(
            name='ProductSizeRelation',
        ),
    ]
