# Generated by Django 5.0 on 2024-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_image_alter_productversion_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='product_images/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
