# Generated by Django 5.0 on 2024-03-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='price'),
            preserve_default=False,
        ),
    ]
