# Generated by Django 5.0 on 2024-03-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='description',
        ),
    ]
