# Generated by Django 5.0 on 2024-03-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_wishlist_options_and_more'),
        ('order', '0003_remove_basketitem_product_version'),
        ('products', '0020_category_title_az_category_title_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVersion',
        ),
    ]
