# Generated by Django 5.0 on 2024-03-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_delete_productversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='kod',
            field=models.CharField(default=1, max_length=100, verbose_name='kod'),
            preserve_default=False,
        ),
    ]
