# Generated by Django 5.0 on 2024-03-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_size_kod_color_kod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='kod',
            new_name='code',
        ),
    ]
