# Generated by Django 5.0 on 2024-01-09 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shippingadress'),
        ('products', '0003_color_size_remove_product_price_productversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wishlist', to='products.productversion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
