# Generated by Django 5.0 on 2024-02-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='message',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default=1, max_length=50, verbose_name='number'),
            preserve_default=False,
        ),
    ]
