# Generated by Django 5.0 on 2024-02-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_message_remove_user_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='message'),
        ),
    ]
