# Generated by Django 5.0 on 2024-02-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_productcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
