# Generated by Django 5.0 on 2024-03-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='adress',
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='address',
            field=models.TextField(default=1, max_length=300, verbose_name='address'),
            preserve_default=False,
        ),
    ]
